### PR TITLE
Chain NER speedups

### PR DESCRIPTION
**Pull request by Craigacp**
These commits improve the speed of the ChainNer feature generation. It uses a few of the tricks from the previous optimisations to StackedChainNer which give small performance bumps and allocate fewer objects. In addition it changes how the "FIRSTMENTION" feature is generated, by swapping it from an O(n^2) operation in the number of tokens to a O(n) operation (by memoising the feature generation). This also reduces the number of strings which are created during the feature generation. It's this latter optimisation which gives the vast majority of the speedup. The new code generates the same features as the current code so it's a drop in replacement that doesn't require retraining the models.

On a quick test running NER tagging on Barack Obama's wikipedia page this reduces the runtime of 20 iterations from 18.7s to 7.7s, so it's about 2.4x faster.

These changes are orthogonal to the ones Philip has a pull request for.

### CODE REVIEW

**Comment by Craigacp** [comment]
Actually, hold off on merging this while I check up on some of the feature generation, looks like I might have introduced a slight difference.

I'll add another comment when I've checked everything through again.

**Comment by Craigacp** [comment]
Ok, it looks like one difference is that when token.prevWindow() is called on the first token in a sequence it returns that token. Ditto for token.nextWindow() with the last token. Given token.prev and token.next both return null in the respective states is this a bug in ChainLink?

**Comment by Craigacp** [comment]
It looks like prevWindow is the bugged bit (rather than the code I replaced it with). prevWindow(0) called on the first token in a sequence returns that token, but prevWindow(0) called on any other token returns an empty list. I would expect both of them to return the empty list. It looks like this odd behaviour is what's causing it to return the first token whenever prevWindow is called on the first token.

I can patch this too (it's only used in the NER and the OntonotesPhraseEntityTypeLabeler), but it feels like that should end up in a separate pull request. It does mean that the models should probably be retrained after this commit is merged in, as they were generating incorrect features at training time.

**Comment by strubell** [comment]
Please do submit another pr with that fix, and I'll deal with merging once
we have re trained models. Thanks!

**Comment by strubell** [comment]
Assuming fixing the prevWindow issue resolves the feature discrepancies you noticed, this pr looks good to me and I'll merge once the other pr is merged

**Comment by Craigacp** [comment]
Ok. We're still checking the rest of the features. It's the same on the test documents I've checked, but we're checking a few others. I've made a patch for the prevWindow/nextWindow issue, I'll make a pull request.

**Comment by Craigacp** [comment]
All the rest of the checks came through, it was just the prevWindow/nextWindow issue that caused some feature differences. You should be ok to merge this now.

**Comment by strubell** [comment]
Great, thanks for the update. Hoping to get to it this weekend (since I'll
have to re-train models)

**Comment by strubell** [comment]
Just an update: due to some issues with our cluster, I wasn't able to re-train models this weekend, but I am working on it

**Comment by Craigacp** [comment]
Hi Emma, did the cluster come back?

Strictly it doesn't require retraining the models as it's just slightly more likely to predict entities at the start and end of a sequence (as they don't have the replicated features which make I more likely than B), and we've ran it a few times on old models (before I figured out the issue).

**Comment by strubell** [comment]
Cluster is fine, but we uncovered a gross bug. I believe I know a
workaround, but then I was busy with other things. TL;DR: hope to do it
this weekend!

**Comment by Craigacp** [comment]
Ok, thanks.

**Comment by strubell** [comment]
Ok, new models are in all-models-1.2-SNAPSHOT

**Pull request merged**
