### PR TITLE
Close file after use

### PR DESCRIPTION
**Pull request by janekdb**
See this thread,

  https://groups.google.com/a/factorie.cs.umass.edu/forum/#!topic/discuss/XsBNCb4uIKY

### CODE REVIEW

**Comment by janekdb** [comment]
First CI build error

```
:: problems summary ::
:::: WARNINGS
		[FAILED     ] org.scala-sbt#main;0.13.8!main.jar: The HTTP response code for https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.8/jars/main.jar did not indicate a success. See log for more detail. (281ms)
```

**Comment by strubell** [comment]
Thanks! Looks like an unrelated sbt issue. I will look into it and merge (so that we don't cause the build to fail)

**Comment by janekdb** [comment]
@strubell - ping me when sbt issue fixed on master. I will rebase and push.

**Comment by strubell** [comment]
Finally got a chance to look in to this, and found that it's fine -- must have been some server issue at the time the travis build ran. Thanks again!

**Pull request merged**
