### PR TITLE
Small changes to Person name parser

### PR DESCRIPTION
**Pull request by nmonath**
1. Handling edge case where name string is ","
2. Added parseFullNameSafe which returns None in the case where parseFullName would throw an exception for invalid/empty name strings.

### CODE REVIEW

**Comment by nmonath** [comment]
I think we also want this on TACKBP2015. What's the best way to do that?

**Comment by strubell** [comment]
We should probably merge the current factorie master into the tackbp2015 branch

**Comment by strubell** [comment]
Alternatively you could submit a PR to the tackbp2015 branch with these changes

**Comment by nmonath** [comment]
Sorry, I was mistaken. we don't need it right now on the tac factorie. I think let's wait on it and when we next merge master into tac2015, we'll have the change.

**Pull request merged**
