### PR TITLE
Build fix: added UMass resolvers, corrected all-models dep, fixes in bin/fac and other

### PR DESCRIPTION
**Pull request by malcolmgreaves**
-- These fixes make `sbt with-nlp-resources:assembly` work as expected.
	-- Added Umass resolver (for both public releases and snapshots).
	-- Changed dependency for all-models to 1.0.0-SNAPSHOT (most
recent).

### CODE REVIEW

**Comment by malcolmgreaves** [comment]
Hi! I was playing around with Factorie when I noticed that `sbt with-nlp-resources:assembly` failed due to a dependency issue. I have fixed the issue with a few modifications to `project/Build.scala`.

**Comment by malcolmgreaves** [comment]
I also noticed problems in `bin/fac` wrt. incorrect name for assembled jar. As well as 2 outdated version numbers in 2 other scripts. I updated these with the most recent commit.

**Comment by malcolmgreaves** [comment]
Also, I think that the use of an sbt script here should be removed in favor of using a system-installed sbt. One can specify that we need sbt 0.13.8 in `project/Build.properties`.

Reason here is that the current sbt script is out of date and no longer works. It tries to grab the sbt launcher with an incorrect URL (it gives a 404).

**Comment by strubell** [comment]
Hi Malcolm, thanks for your fixes! Can you merge the latest changes (this should fix the sbt script.)

Also, did you find that the dependency on all-models-1.0.0 (versus the snapshot version) didn't work (after adding the UMass resolver)? all-models-1.0.0 should be the correct models dependency... despite the existence of a models snapshot, we don't actually use snapshot versions of models, only releases.

**Comment by malcolmgreaves** [comment]
Hi Emma! I can certainly merge the latest changes. I will also revert the all-models dep in this PR to 1.0.0 I was only attempting to find the minimal set of changes that enabled me to get that sbt command working.

**Comment by strubell** [comment]
Hi Malcolm, are you still planning on updating this PR? We're looking to do a release sometime soon so I'm trying to get pending PRs merged before that.

**Comment by malcolmgreaves** [comment]
Ah! My apologies for letting this go by the wayside! I have pushed the changes you've asked for. Looks like it's all good!

**Comment by strubell** [comment]
Great, thanks!

**Pull request merged**
